### ISSUE TITLE
MacOS Support?

### ISSUE THREAD

**Issue by Androz2091** [7coil/DiscordForOffice#10]
Actually there are only `.exe` files, is it possible to make the same things for Mac OS?

**Comment by 7coil** [comment]
Unfortunately, I do not have access to a MacOS system.

I therefore cannot develop for MacOS.

**Comment by Androz2091** [comment]
It's a shame, there are several of us working on MacOS and it would be great to be able to make it work on MacOS. 😢

**Comment by 7coil** [comment]
If anyone happens to have a MacOS device and would like to work on VSTO extensions for MacOS X, please send a reply.
Otherwise, this is dead in the ground.

**Comment by insomnia-creator** [comment]
Hey I have a macos device and would be willing to help.

**Comment by 7coil** [comment]
I don't know how you're going to go about doing this, but good luck.

**Comment by DexterHaxxor** [comment]
> Actually there are only `.exe` files, is it possible to make the same things for Mac OS?

.NET uses .exe files on all platforms. If it doesn't work out of the box, try just compiling it yourself.

**Comment by 7coil** [comment]
Pretty sure MacOS doesn't support the VSTO anyway, will check soon
