### ISSUE TITLE
error with install

### ISSUE THREAD

**Issue by strannikz** [7coil/DiscordForOffice#11]
![Screenshot_2](https://user-images.githubusercontent.com/37824432/77683907-f9934580-6fba-11ea-981e-b18c7f10de33.png)
(notice: I allowed the site)

**Comment by TheArcaneBrony** [comment]
Same issue here, log:
```(5/27/2020 4:35:22 PM) Downloading 'DotNetFX48\NDP48-Web.exe' from 'http://go.microsoft.com/fwlink/?LinkId=2053982&clcid=0x409' to 'C:\Users\ADMINI~1\AppData\Local\Temp\1\VSD2F7D.tmp\'
Download completed at 5/27/2020 4:35:22 PM
Downloading failed with HRESULT=-2146697202```

An error occurred downloading the following resource:
http://go.microsoft.com/fwlink/?LinkId=2053982&clcid=0x409

os (in my case) windows server 2019

**Comment by 7coil** [comment]
I have no idea what is going on.

**Comment by strannikz** [comment]
> I have no idea what is going on.

ehm... so, i reinstall my windows (not for this), and decide to try again. same issue.

**Comment by Mystik01** [comment]
thwe website is blocked, you know on the releases page it says trust the webste.
I assume you have done that, but if you actually go to [https://office.terminal.ink/](https://office.terminal.ink/) on your web broser it has an error.
This prject is basically broken.

**Comment by 7coil** [comment]
Hello!

I have recently been transferred the rights to this domain name.
I shall fix the DNS issues which causes failure to resolve the office.terminal.ink domain name as soon as I can.

Thanks

**Comment by Mystik01** [comment]
Oh wow that was quick reply, thanks.
also thanks for putting your hard work into this project

**Comment by 7coil** [comment]
If you're curious, the changes have now been done.
Downloads should work again.

**Comment by Mystik01** [comment]
`An error occurred trying to download 'https://office.terminal.ink/DiscordForWord.vsto'.

The following components were successfully installed:
- Microsoft .NET Framework 4.8 (x86 and x64)

See the setup log file located at 'C:\Users\logan\AppData\Local\Temp\VSD1AAD.tmp\install.log' for more information.`



![image](https://user-images.githubusercontent.com/65687597/89819913-0d8fac00-db44-11ea-9ed4-f5f9ee18f333.png)

**Comment by 7coil** [comment]
How strange, am error with a success message.

Try sending the log file specified so I can try to understand what the hell is going on.

Thanks

**Comment by Mystik01** [comment]
[install.log](https://github.com/7coil/DiscordForOffice/files/5052910/install.log)

**Comment by strannikz** [comment]
yea, tested after improvments, same issue, just like mystik

**Comment by 7coil** [comment]
GitHub will provision a HTTPS certificate to me soon.
It's just a question of when. (even though it says it has already been done)

![image](https://user-images.githubusercontent.com/13886925/89827916-3027c200-db50-11ea-9373-bfea0fff6e7b.png)

**Comment by Mystik01** [comment]
ok alright

**Comment by 7coil** [comment]
The HTTPS certs have been deployed.
Hopefully, the issues will be fixed.

**Comment by strannikz** [comment]
> The HTTPS certs have been deployed.
> Hopefully, the issues will be fixed.

thank you. issue was fixed.
