### ISSUE TITLE
Doesn't work despite adding to trusted sites

### ISSUE THREAD

**Issue by berrely** [7coil/DiscordForOffice#17]
I added https://office.terminal.ink/ to trusted sites and tried to run `word.exe` from releases, but I still get this error: 
https://i.imgur.com/U6b4au2.png
Any ideas?

**Comment by 7coil** [comment]
Good news - I've made a new installer.

https://github.com/7coil/DiscordForOffice/releases/tag/1.1.1

Because of this, the ClickOnce issue shall no longer exist.
