### ISSUE TITLE
Support for Microsoft Teams

### ISSUE THREAD

**Issue by Mystik01** [7coil/DiscordForOffice#19]
Is it possible to add 365 Teams support? I know teams does let you make extensions/bots and stuff so might be possible?

**Comment by 7coil** [comment]
Microsoft Teams does not have an extension system that can be hooked into, so this will not be possible without some software listening to whats going on.

Sorry!

**Comment by experi18** [comment]
damn... it would be awesome to have a microsoft teams integrated with discord :(
