### ISSUE TITLE
Not a single version of DiscordForOffice detecting any Office application

### ISSUE THREAD

**Issue by Leronus** [7coil/DiscordForOffice#24]
Latest release 1.1.1 64-bits & 32-bits, as well as pre-release 1.2 did not work.
I have 64-bits Windows 10 and 64-bits Microsoft Word, opened within Office 365.
Discord version: Stable 85347 (cc28942)
Prior to installing I did not have any older versions of DiscordForOffice.
Discord does not detect any Office application.

**Comment by Leronus** [comment]
Never mind, it works very nicely

**Comment by 7coil** [comment]
Excellent news.
